### ISSUE TITLE
How to compile / build?

### ISSUE THREAD

**Issue by ottadini** [jonasfrantz/g3data2#2]
What is the process to build and install this code?

Are these source files drop-in replacements for the correspondingly-named source files in the gtk2 g3data package also hosted here on github by pn2200?

**Comment by jonasfrantz** [comment]
g3data2 is built by Makefile, i.e. the command 'make' in the source folder
should do it. Of course, you need gtk+ 3.x installed for it to work.

Best regards,

Jonas

On Mon, Oct 15, 2012 at 7:38 AM, hairyson notifications@github.com wrote:

> What is the process to build and install this code?
> 
> Are these source files drop-in replacements for the correspondingly-named
> source files in the gtk2 g3data package also hosted here on github by
> pn2200?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jonasfrantz/g3data2/issues/2.

## 

Jonas Frantz
Email: jonas@frantz.fi
Phone: +358405365826
WWW: http://www.frantz.fi

**Comment by ottadini** [comment]
I have it already, but just didn't have the 'dev' package. Sorry for the hassle.
